schema_version = "1.0.0"

id = "leomoon_bezier2svg"
version = "2.0.0"
name = "LeoMoon Bezier2SVG"
tagline = "Export Blender bezier curves as SVG files"
maintainer = "Amin Babaeipanah <contact@leomoon.com>"
type = "add-on"

website = "https://leomoon.com/downloads/plugins/leomoon-bezier2svg/"

tags = ["Import-Export"]

blender_version_min = "5.1.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

# Files/folders to exclude from the built .zip
[build]
paths_exclude_pattern = [
  "__pycache__/",
  "*.pyc",
  "*.zip",
  ".git/",
  "tests/",
  "legacy/",
]
